### PR TITLE
Add withHeader to openapi-plugin

### PR DESCRIPTION
**Pull request by benjvoigt**

### CODE REVIEW

**Comment by nexsja** [comment]
@benjvoigt can you please add a test that covers withHeaders? 
Might help get this merged sooner. :)

**Comment by TimoFrye** [comment]
@benjvoigt @nexsja  here you go =)

**Comment by nexsja** [comment]
Thank you! :)

@outofcoffee ping :)

**Comment by outofcoffee** [comment]
Thanks, both.

**Pull request merged**
