### PR TITLE
feat: security request header regex operator

### PR DESCRIPTION
**Pull request by matejkobza**
Hello, please check my proposed solution. I am not a kotlin developer, this was my first attempt to write something we would like to have as part of imposter.

We are missing check for oauth authorization header:
Authorization: Bearer [access_token]

### CODE REVIEW

**Comment by outofcoffee** [comment]
This is a great contribution. Thank you very much.

**Review by outofcoffee — APPROVED** [review]
I have updated the operator enum value to `Matches` and also added `NotMatches` to align with how request match operators work.

Tests and docs also updated.

**Comment by outofcoffee** [comment]
Released in [v3.24.0](https://github.com/outofcoffee/imposter/releases/)

**Comment by matejkobza** [comment]
Thank you

**Pull request merged**
